// This file is auto-generated by Elfra Config Tool
// Do not edit this file directly.
export const config = {
  colors: {
    primary: "#669c35",
    secondary: "#aaaaaa",
    accent: "#fde1af",
    dark: "#0e0e11",
    bright: "#ffffff",
    success: "#00DC82",
    warn: "#fcc800",
    error: "#ff6467",
  },
  font: 'Roboto',
  fontprovider: 'google',
  auth: {
    enabled: false,
  },
  institution: {
    name: 'saftladen',
    web: 'saftladen.de',
  },
  topics: [
    { name: 'IT', color: 'pink' },
    { name: 'Security', color: 'purple' },
  ],
};
