// This file is auto-generated by Elfra Config Tool
// Do not edit this file directly.
export const config = {
  colors: {
    primary: "#669c35",
    secondary: "#aaaaaa",
    accent: "#fde1af",
    dark: "#0e0e11",
    bright: "#ffffff",
    success: "#00DC82",
    warn: "#fcc800",
    error: "#ff6467",
  },
  font: "Roboto",
  fontprovider: "google",
  auth: {
    // supabase is used for authentication, so you need to set the environment variables SUPABASE_URL and SUPABASE_KEY in your .env file.
    // This means you can only use Authentication, if you have set up a Supabase project.
    enabled: true,
    oAuth: {
      // Only set the oAuth provider to true, if you have set up the provider in your Supabase project.
      // If you don't want to use a provider, set it to false.
      google: false,
      facebook: false,
      github: true,
      twitter: false,
      discord: false,
      apple: false,
      microsoft: false,
      keycloak: false,
    },
  },
  institution: {
    name: "saftladen",
    web: "saftladen.de",
  },
  topics: [
    { name: "IT", color: "pink" },
    { name: "Security", color: "purple" },
  ],
};
